# Generated by Django 3.1.3 on 2022-08-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_auto_20220809_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='imgFile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
