# Generated by Django 3.1.3 on 2022-08-11 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_question_imgfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='imgFile',
            new_name='imgfile',
        ),
    ]
