# Generated by Django 3.1.3 on 2022-08-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_auto_20220811_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='imgfile',
        ),
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
