# Generated by Django 3.1.3 on 2022-08-16 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0010_auto_20220811_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.question')),
            ],
        ),
    ]
