# Generated by Django 3.1.3 on 2022-08-18 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0011_fileform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileForm',
            new_name='FileModel',
        ),
    ]
