# Generated by Django 3.1.3 on 2022-08-18 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0012_auto_20220818_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='file',
        ),
    ]
